# Generated by Django 2.0.5 on 2018-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180609_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(1, '待评判'), (2, '已评判'), (3, '迟交'), (4, '已下载')], default=1),
        ),
    ]
