# Generated by Django 2.0.5 on 2018-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Scores',
            field=models.IntegerField(default=0),
        ),
    ]
