# Generated by Django 2.0.5 on 2018-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_record_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Scores',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.FloatField(choices=[(1, '待评判'), (2, '已评判'), (3, '迟交'), (4, '已下载')], default=1),
        ),
    ]
