# Generated by Django 2.0.5 on 2018-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='链接'),
        ),
    ]
