# Generated by Django 2.0.5 on 2018-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='链接'),
        ),
    ]
