# Generated by Django 2.0.5 on 2018-05-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('body', models.TextField(max_length=1000, verbose_name='正文')),
                ('staus', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=1024)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logReg.Article')),
                ('p_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_child_comment', to='logReg.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('Teac', 'Teacher'), ('stu', 'Student')], default='stu', max_length=10, verbose_name='身份')),
                ('stu_id', models.CharField(max_length=30, unique=True, verbose_name='学号/工作号')),
                ('college_name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30, verbose_name='昵称')),
                ('passwd', models.CharField(max_length=30, verbose_name='密码')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logReg.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logReg.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logReg.Category', verbose_name='栏目'),
        ),
    ]
