# Generated by Django 2.0.5 on 2018-06-05 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='Student_name',
            field=models.ForeignKey(default='44436', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
