# Generated by Django 2.0.5 on 2018-06-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180605_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='Student_name',
            new_name='Student',
        ),
    ]
