# Generated by Django 2.0.5 on 2018-06-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0003_auto_20180605_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_time', models.DateTimeField()),
                ('File', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='Status',
        ),
        migrations.AddField(
            model_name='record',
            name='Homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Homework'),
        ),
        migrations.AddField(
            model_name='record',
            name='Student',
            field=models.ForeignKey(default='44436', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
