# Generated by Django 2.0.5 on 2018-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_record_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Scores',
            field=models.FloatField(default=0),
        ),
    ]
